server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: serie-service
  data:
    mongodb:
      username: usr-serie-service-mongo
      password: pwd-serie-service-mongo
      database: serie-service-dev-mongo
      port: 27017
      host: localhost
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: serie-service

eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/